@startuml

'!include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/materia-outline/puml-theme-materia-outline.puml

participant "End-user" as enduser
participant "Merchant" as merchant
participant "Service" as service
database "Database" as DB

autonumber
activate enduser
activate merchant
merchant -> enduser: open QR code

activate service
enduser -> service: call check-in API including parking_lot_id and user_id

service -> service: validate parking_lot_id and user_id

activate merchant
service -> merchant: request information from merchant
merchant --> service: send license_plate and vehicle_type
service -> service: validate license_plate and vehicle_type

activate DB
service -> DB: check if e-ticket created before

alt e-ticket is not created before
    DB --> service: return true
    service -> DB: insert new ticket including license_plate, user_id and parking_lot_id
    DB --> service: insert success
    service --> merchant: send message create e-ticket sucess
    service --> enduser: send e-ticket infomation

else the license plate with user ID and parking lot ID is exist
    DB --> service: return false
    deactivate DB
    service --> merchant:send message e-ticket was created before
    deactivate merchant
    service --> enduser: send message check-in fail
    deactivate enduser
    deactivate service
end



@enduml
